### PR TITLE
Added Skull Skin Parser

### PR DESCRIPTION
**Pull request by mmuziek**
Added a Skull Parser that shows the Skull Skin if there is a Skin.
Based on the NBT it contains
Next up Enchantments!

### CODE REVIEW

**Comment by mmuziek** [comment]
this request implements the Skin Parser for Skulls
and i added 2 Fixes 1 for the Skull Texture NBT Parser and the other one for the Names sometimes be different in the NBT strange enough.

**Comment by rodel77** [comment]
In the latest commit `9cf98691b0f5cbed3d5e448f4d37836b4ccde97b` i changed i little bit the skull system, instead of saving the image in filesystem just strip and scale it with a css trick

**Comment by rodel77** [comment]
I also added support for old skins (64x32) with css percentage

**Comment by mmuziek** [comment]
i did the saving for a reason
Mojang does not allow more connections then a certain from a single IP.
if i cache the image we only need to load the missing ones causing a way lower request on the mojang servers....

**Comment by rodel77** [comment]
Theres no docs about textures endpoint but also theres no headers that tells any limit, you have limit to fetch uuid, names and profiles but nothing in textures, after refreshing my page with 5 heads crazily the images displayed correctly, i check the headers and i seems like they already cache the skins

**Comment by mmuziek** [comment]
well i found it out the hard way but if you want everyone to have this problem its your choice.
at testing my script first hour it works correctly after that i walked against cannot connect error to the texture server after searching and reading its a block of 15 minutes due to to much connections.
and indeed after 15 minutes i could get another set of images and then i was blocked again.
so to be short it does block you if you get to much at the same time.
beside that i think that its quicker to load it from own server then mojang because if mojang is down for whatever reason again. this web page does not work with skulls if using your way

**Comment by rodel77** [comment]
Do you have screenshots of that error?

**Pull request merged**
